name: Build/release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        # os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        # Import Apple API key for app notarization on macOS
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.MACOS_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.MACOS_API_KEY_ID }}.p8

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          API_KEY_ID: ${{ secrets.MACOS_API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.MACOS_API_KEY_ISSUER_ID }}
        with:
          mac_certs: ${{ secrets.MACOS_CERTIFICATE_APPLICATION}}
          mac_certs_password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD}}
          windows_certs: ${{ secrets.WINDOWS_CERTIFICATE_APPLICATION}}
          windows_certs_password: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD}}
          github_token: ${{ secrets.github_token}}

          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          max_attempts: 5
